name: Update copyright year

on:
  schedule:
    - cron: "0 0 1 1 *" # Midnight UTC on January 1st
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-copyright-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update year in LICENSE
        run: |
          CURRENT_YEAR=$(date +'%Y')
          sed -i -E "s/Copyright \(c\) ([0-9]{4})(-[0-9]{4})?/Copyright (c) \1-$CURRENT_YEAR/" LICENSE

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update copyright year to $(date +'%Y')"
          branch: automated/update-copyright-year
          delete-branch: true
          title: "Update copyright year"
          body: "Automated update of copyright year in LICENSE file."
          labels: automated

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run: gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ github.token }}
